inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  Enabled: false
