inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/LineLength:
  Max: 120

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Naming/VariableNumber:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false
